server:
  port: 8888

spring:
  applcation:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: file://C:\workspace\Spring\spring-cloud-ecommerce


management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
